version: '3.8'

services:
    dev:
        container_name: tree-toolbox_api_dev
        image: tree-toolbox-api-dev:1.0.0
        build:
            context: .
            target: development
            dockerfile: ./Dockerfile
        command: npm run start:debug
        ports:
            - 3000:3000
            - 8080:8080
            - 9229:9229
        networks:
            - app-network
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        environment:
            - DATABASE_URL=postgresql://toolbox:toolbox@db:5432/toolbox
        restart: unless-stopped
    # prod:
    #    container_name: tree-toolbox_api_prod
    #    image: tree-toolbox-api-prod:1.0.0
    #    build:
    #        context: .
    #        target: production
    #        dockerfile: ./Dockerfile
    #    command: npm run start:prod
    #    ports:
    #        - 3000:3000
    #        - 8080:8080
    #        - 9229:9229
    #    networks:
    #        - app-network
    #    volumes:
    #        - .:/usr/src/app
    #        - /usr/src/app/node_modules
    #    environment:
    #        - DATABASE_URL=postgresql://toolbox:toolbox@db:5432/toolbox
    #    restart: unless-stopped
    # 
    db:
        image: postgres:latest
        restart: always
        volumes:
            - db-volume:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - app-network
        environment:
            - POSTGRES_PASSWORD=toolbox
            - POSTGRES_USER=toolbox
            - POSTGRES_DB=toolbox

    adminer:
        image: adminer:latest
        restart: always
        ports:
            - "8081:8080"
        depends_on:
            - db
        networks:
            - app-network
networks:
    app-network:

volumes:
  db-volume:
    